### ISSUE TITLE
Webapp Feedback

### ISSUE THREAD

**Issue by linknum23** [micro-nova/AmpliPi#34]
Jason:
- [x]  Hard to tell whats playing
- [x] Slow when changing whole house volume
- [x] Can groups be subgrouped? This could be used to handle whole house
- [ ] The 2 second refresh resets the source choices if you are currently in the process of picking a new one #254 
- [x] Whole house maxed volume after change sometimes
- [x] #392 

Lincoln:
- [ ] #73 

Matthew:
- [ ] #334
- [x] Zone 1 shouldn't be at bottom, it should be at TOP!   Groups go below zone maybe?
  - [x] Michael - maybe just remove all groups from the default config?
- [x] Rename shairport stream name to airplay in stream selection
- [ ] Quick start should tell user how to configure Pandora before using it.
- [x] Remove most of the streams from the default config.
- [x] Can zones be removed from a source? #332 

Ben
- [ ] Consider a zone (and group) based view #211 

Mark:
- [x] Fix horizontal scrolling bug on small iphone 6
- [x] Volume sliders are laggy

Ed:
- [x] Add Group or Zone should really be a multi-selector #228 

Michael:
- [x] The web interface's source selector should include the type of stream (Spotify, Analog X, DLNA, etc.)
- [x] #331
- [ ] Sources, groups, and zones should be shown in a diagram on the API page
- [x] In the API documentation, it would be helpful to have a "Get available {Source/Group/Zone} IDs"
- [x] #332
- [ ] #568
- [ ] To mirror the Pandora interface, change the heart to a thumbs up (just Michael's suggestion)
- [x] Add the ability to export/import config
- [x] Don't fail loading config when a stream doesn't exist (basically support best-effort config loading)
- [x] Give feedback when a config is loaded to show success or failure
- [ ] For the configuration section:
  - [ ] Rename all the "Stream" wording to "Input" in the Inputs config section
  - [ ] Rename Management to Configuration
  - [x] #362

Rick:
- [x] Add PI reset button #284
- [x] #330

Olek:
- [ ] Add offline indicator for when you can connect to AmpliPi but it cant connect to the internet #326

**Comment by sumnerboy12** [comment]
Would be nice to have a "zone centric" view - i.e. you select a zone and then pick an input to play on that zone. This seems more intuitive to me, as an end user, rather than selecting an input and then picking which zones to play it on.

It would also make it easier to use the web app for wall mounted control screens - you could lock the screen to the zone page of the room it is in - and allow users to select which input to play.

**Comment by linknum23** [comment]
> Would be nice to have a "zone centric" view - i.e. you select a zone and then pick an input to play on that zone. This seems more intuitive to me, as an end user, rather than selecting an input and then picking which zones to play it on.
> 
> It would also make it easier to use the web app for wall mounted control screens - you could lock the screen to the zone page of the room it is in - and allow users to select which input to play.

I added your feedback and started thinking about an interface for it at #211. Lets continue the conversation over there :)

**Comment by SteveMicroNova** [comment]
This issue might be outdated due to the onset of Webapp 2
Might be worth seeing what's still relevant and then closing this issue

**Comment by linknum23** [comment]
Yup this is all completed by the new UI or documented somewhere else.
